---
version: "2.1"
services:
  nginx:
    image: arevindh/homelab-tracker
    container_name: homelab-tracker
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped