#!/usr/bin/with-contenv bash

# Set up script

# Check for DB
if [ ! -f /config/www/storage/database/homelab.sqlite ]; then
    echo "Database file not found! Creating empty database"
    touch /config/www/storage/database/homelab.sqlite
else
    echo "Database file exists"
    chown abc:abc /config/www/storage/database/homelab.sqlite
fi


# Check for .env
if [ ! -f /config/www/.env ]; then
    echo "Env file not found! Creating .env file"
    cp /config/www/.env.example /config/www/.env
else
    echo "Env file exists"
fi


echo "Running database migrations"
php /config/www/artisan migrate

# Check app key exists
if grep -E "APP_KEY=[0-9A-Za-z:+\/=]{1,}" /config/www/.env > /dev/null; then
    echo "App key exists"
else
    echo "Generating app key"
    php /config/www/artisan key:generate
fi

php /config/www/artisan speedtest:install

php /config/www/artisan speedtest:run

echo "Clearing old jobs from queue"
php /config/www/artisan queue:clear

chown -R abc:abc /config

chmod +x /config/www/storage/speedtest-cli/cli/speedtest

cp /config/docker/conf/defaults/crontab /etc/crontabs/root