name: Laravel

on:
  push:
    branches: [ docker-dev ]
  pull_request:
    branches: [ docker-dev ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate

    - name: Get node.js cache directory
      id: node-cache-dir
      run: echo "::set-output name=dir::$(npm config get cache)" # Use $(yarn cache dir) for yarn

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.node-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # Use '**/yarn.lock' for yarn
        restore-keys: ${{ runner.os }}-node-

    - name: Install npm
      run: npm install && npm run dev
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p storage/database
        touch storage/database/homelab.sqlite
    - name: Migrate DB
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: storage/database/homelab.sqlite
      run: php artisan migrate
  
  build:
    needs: laravel-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: package docker
      run: |
        VERSION=$(date +%s)
        docker login --username arevindh --password ${{ secrets.DOCKER_ACCESS_TOKEN }}
        docker build . --file Dockerfile --tag arevindh/homelab-tracker:latest
        docker push arevindh/homelab-tracker:latest
      env:
        CI: true